name: FakeMT
version: ${project.version}
main: fakemt.fakemt.FakeMT
authors: [ KingDev ]
description: Plugin die de FakeMT server van handig/leukigheid voorzien
commands:
  autolore:
    description: Geef al de items in je inventaris een gepaste lore
  kit:
    description: Maak bepaalde kits aan
  autoenchant:
    description: Enchant al de mogelijke items in je inventaris met de gevraagde enchantment
  links:
    description: Krijg de nodige informatie over de server te zien
  fastlore:
    description: Zet automatisch de lore van een item in je hand
  fastname:
    description: Zet automatisch de naam van een item in je hand
  alert:
    description: Verzend een broadcast naar de complete server